function(string_prefix variable)
  foreach(v ${ARGN})
    if(NOT ${variable})
      set(${variable} "${v}")
    else()
      string(FIND "${${variable}}" "${v}" r)
      if(${r} EQUAL -1)
        set(${variable} "${v} ${${variable}}")
      endif()
    endif()
  endforeach()
  set(${variable} "${${variable}}" PARENT_SCOPE)
endfunction()

function(string_append variable)
  foreach(v ${ARGN})
    if(NOT ${variable})
      set(${variable} "${v}")
    else()
      string(FIND "${${variable}}" "${v}" r)
      if(${r} EQUAL -1)
        set(${variable} "${${variable}} ${v}")
      endif()
    endif()
  endforeach()
  set(${variable} "${${variable}}" PARENT_SCOPE)
endfunction()

function(string_remove variable)
  foreach(v ${ARGN})
    string(REPLACE "${v} " "" ${variable} "${${variable}}")
    string(REPLACE "${v}" "" ${variable} "${${variable}}")
  endforeach()
  set(${variable} "${${variable}}" PARENT_SCOPE)
endfunction()

function(list_append variable)
  foreach(v ${ARGN})
    if(NOT ${v} IN_LIST ${variable})
      list(APPEND ${variable} ${v})
    endif()
  endforeach()
  set(${variable} ${${variable}} PARENT_SCOPE)
endfunction()

function(list_remove variable)
  foreach(v ${ARGN})
    if(${v} IN_LIST ${variable})
      list(REMOVE_ITEM ${variable} ${v})
    endif()
  endforeach()
  set(${variable} ${${variable}} PARENT_SCOPE)
endfunction()
