# core
macro(string_prefix variable)
  foreach(v ${ARGN})
    if(${variable})
      string(FIND "${${variable}}" ${v} r)
      if(${r} EQUAL -1)
        set(${variable} "${v} ${${variable}}")
      endif()
      unset(r)
    else()
      set(${variable} ${v})
    endif()
  endforeach()
endmacro()

macro(string_append variable)
  foreach(v ${ARGN})
    if(${variable})
      string(FIND "${${variable}}" ${v} r)
      if(${r} EQUAL -1)
        set(${variable} "${${variable}} ${v}")
      endif()
      unset(r)
    else()
      set(${variable} ${v})
    endif()
  endforeach()
endmacro()

macro(string_remove variable)
  foreach(v ${ARGN})
    string(REPLACE "${v} " "" ${variable} "${${variable}}")
    string(REPLACE "${v}" "" ${variable} "${${variable}}")
  endforeach()
endmacro()

macro(list_append variable)
  foreach(v ${ARGN})
    if(NOT ${v} IN_LIST ${variable})
      list(APPEND ${variable} ${v})
    endif()
  endforeach()
endmacro()

macro(list_remove variable)
  foreach(v ${ARGN})
    if(${v} IN_LIST ${variable})
      list(REMOVE_ITEM ${variable} ${v})
    endif()
  endforeach()
endmacro()
